services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ideal-app
    container_name: ideal-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - ideal-network

  db:
    image: mysql:8.0
    container_name: ideal-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ideal
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ideal-dbdata:/var/lib/mysql
    networks:
      - ideal-network
      
  nginx:
    image: nginx:alpine
    container_name: ideal-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - ideal-network

networks:
  ideal-network:
    driver: bridge

volumes:
  ideal-dbdata:
    driver: local